import os
from typing import List, Dict, Optional, Any
from groq import Groq, GroqError
from tenacity import retry, stop_after_attempt, wait_fixed
from loguru import logger

class GroqClient:
    """
    A wrapper around the Groq SDK to handle generation, chat, retries, and config.
    """
    def __init__(self, api_key: Optional[str] = None):
        """
        Initializes the Groq client.
        """
        from dotenv import load_dotenv
        load_dotenv()
        
        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        if not self.api_key:
            raise ValueError("GROQ_API_KEY is not set. Please provide it or set it in .env.")
            
        self.client = Groq(api_key=self.api_key, timeout=float(os.getenv("GROQ_TIMEOUT", "30.0")))
        self.default_model = os.getenv("MODEL_NAME", "qwen")
        self.default_temperature = float(os.getenv("TEMPERATURE", "0.0"))
        self.default_max_tokens = int(os.getenv("MAX_TOKENS", "512"))

    def _clean_response(self, text: str) -> str:
        """
        Removes <think>...</think> tracing blocks generated by reasoning models.
        """
        import re
        if not text:
            return ""
        return re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

    @retry(stop=stop_after_attempt(3), wait=wait_fixed(2), reraise=True)
    def generate(self, prompt: str, model: Optional[str] = None, temperature: Optional[float] = None, max_tokens: Optional[int] = None, stream: bool = False, clean_think: bool = True) -> Any:
        """
        Generates a text completion for a single string prompt.
        """
        if not prompt.strip():
            raise ValueError("Prompt cannot be empty.")
            
        messages = [{"role": "user", "content": prompt}]
        return self.chat(messages, model=model, temperature=temperature, max_tokens=max_tokens, stream=stream, clean_think=clean_think)

    @retry(stop=stop_after_attempt(3), wait=wait_fixed(2), reraise=True)
    def chat(self, messages: List[Dict[str, str]], model: Optional[str] = None, temperature: Optional[float] = None, max_tokens: Optional[int] = None, stream: bool = False, clean_think: bool = True) -> Any:
        """
        Generates a text completion for a list of chat messages.
        """
        if not messages:
            raise ValueError("Messages cannot be empty.")
            
        for msg in messages:
            if "role" not in msg or "content" not in msg:
                raise ValueError("Each message must contain 'role' and 'content' keys.")
            
        target_model = model or self.default_model
        target_temp = temperature if temperature is not None else self.default_temperature
        target_tokens = max_tokens if max_tokens is not None else self.default_max_tokens
        
        try:
            logger.debug(f"Sending chat request to Groq model {target_model} (stream={stream})")
            response = self.client.chat.completions.create(
                messages=messages,
                model=target_model,
                temperature=target_temp,
                max_tokens=target_tokens,
                stream=stream
            )
            if stream:
                return response
                
            raw_content = response.choices[0].message.content
            if clean_think:
                return self._clean_response(raw_content)
            return raw_content
        except GroqError as e:
            logger.error(f"Groq API Error: {e}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error during Groq generation: {e}")
            raise

    def health_check(self) -> bool:
        """
        Tests if the Groq client is configured and can connect successfully by listing available models.
        """
        try:
            self.client.models.list()
            return True
        except Exception as e:
            logger.warning(f"Groq health check failed: {e}")
            return False
